### ISSUE TITLE
Creating issue templates

### ISSUE THREAD

**Issue by Softwarekang** [Softwarekang/knetty#35]
add issues template for various types such as Feature, Bug, Docs, and Question.

**Comment by Chever-John** [comment]
Pls, assign this issue to me.
I will solve it.

**Comment by Softwarekang** [comment]
thanks for cheer-john:thumbsup:

**Comment by Chever-John** [comment]
Hello, Let us confirm what kind of issues template we need.

[Issue template](https://github.com/apache/apisix/tree/master/.github/ISSUE_TEMPLATE) from Apache APISIX
[Issue template](https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE) from kubernetes

Or if you have better suggestions?
